### ISSUE TITLE
Aint working for me :(

### ISSUE THREAD

**Issue by Aviad94** [hijamoya/PickerViewCell#3]
for some reason it doesnt work with me while using tableview (static), would love to get help :) when i say that it doesnt work i mean it doesnt pop up the pickerview

**Comment by hijamoya** [comment]
Hi, you can refer the sample project, which is also a static table view
<img width="867" alt="Screen Shot 2020-06-21 at 1 55 13 PM" src="https://user-images.githubusercontent.com/1138399/85217827-1d520600-b3c7-11ea-81fc-cd873fb55b1b.png">

**Comment by Aviad94** [comment]
I see, but for some reason it doesnt work for me :( even tho i did what u have told to do

**Comment by Aviad94** [comment]
it was my made, i was an idiot and didnt use it right lol, must say awesome pod bro <3

**Comment by hijamoya** [comment]
OK. Could you please give a star to the library if it helps you.
